### ISSUE TITLE
Training Dataset and Script

### ISSUE THREAD

**Issue by doshiyr** [taiwotman/TensorflowPredictCongestionTypes#1]
Hi @taiwotman , I am working on a similar project and would love to contribute to this project. Would you able to provide training dataset and script that your DL model is trained on? It would be really helpful for my project.

**Comment by taiwotman** [comment]
I have provided you the link to trained and test data. Good luck with your project.

**Comment by taiwotman** [comment]
I have provided you the link to trained and test data. Good luck with your project.
